workflows:
  openlineage-integration-publish:
    jobs:
      - build-integration-sql:
          name: build-integration-sql-all
          matrix:
            parameters:
              image: [
                "quay.io/pypa/manylinux2014_x86_64",
                "quay.io/pypa/manylinux2014_i686",
                "quay.io/pypa/manylinux_2_24_x86_64",
                "quay.io/pypa/manylinux_2_24_i686",
                "messense/manylinux2014-cross:aarch64",
                "messense/manylinux_2_24-cross:aarch64",
              ]
              resource_class: [ "medium" ]
              run_tests: [ false ]
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
            branches:
              ignore: /.*/
      - publish-snapshot-python:
          filters:
            branches:
              only: main
          context: release
          requires:
            - build-client-python
            - build-integration-common
            - build-integration-airflow
            - build-integration-dbt
            - build-integration-dagster
            - build-integration-sql-all
      - publish-spec:
          filters:
            branches:
              only: main
          context: release
      - workflow_complete:
          requires:
            - publish-snapshot-python
            - publish-spec
